name: Build Vernard

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        platform: [x64, x86, ARM64]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore Tools
      run: dotnet tool restore

    - name: Restore Application
      run: msbuild Vernard /t:Restore /p:Configuration=Release

    - name: Decode PFX
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.BASE64_ENCODED_PFX }}")
        $certificate = "GithubAction.pfx"
        [IO.File]::WriteAllBytes("$certificate", $pfx_cert_byte)
        ls

    - name: Build Application Package
      run: msbuild Vernard /p:Configuration=Release /p:Platform=${{ matrix.platform }} /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxBundle=Never /p:PackageCertificateKeyFile=GithubAction.pfx /p:AppxPackageDir="Packages" /p:GenerateAppxPackageOnBuild=true

    - name: Remove PFX
      run: Remove-Item -path GithubAction.pfx

    - name: Upload MSIX package
      uses: actions/upload-artifact@v2
      with:
        name: MSIX Package
        path: Vernard\\Packages